version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        - SECRET_KEY_BASE_DUMMY
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: ${SECRET_KEY_BASE_DUMMY}

volumes:
  pgdata:
